"""
authorization_engine.py

Universal Authorization Engine

Features:
- RBAC
- ABAC
- Policy evaluation
- Permission inheritance
- Audit logging
- Multi-tenant support
- Delegation hooks
- Extensible policy providers

Author: Generated by GPT-5
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, List, Set, Optional, Any, Callable
from enum import Enum
from abc import ABC, abstractmethod
from datetime import datetime
import uuid
import logging

logging.basicConfig(level=logging.INFO)

logger = logging.getLogger("AuthorizationEngine")


# ---------------------------------------------------
# ENUMS
# ---------------------------------------------------

class Decision(Enum):
    ALLOW = "allow"
    DENY = "deny"
    ABSTAIN = "abstain"


# ---------------------------------------------------
# PERMISSION
# ---------------------------------------------------

@dataclass(frozen=True)
class Permission:
    name: str
    description: str = ""


# ---------------------------------------------------
# ROLE
# ---------------------------------------------------

@dataclass
class Role:

    name: str

    permissions: Set[Permission] = field(default_factory=set)

    inherits: Set[str] = field(default_factory=set)

    def add_permission(self, permission: Permission):

        self.permissions.add(permission)

    def remove_permission(self, permission: Permission):

        self.permissions.discard(permission)


# ---------------------------------------------------
# USER
# ---------------------------------------------------

@dataclass
class User:

    id: str

    username: str

    tenant: str = "default"

    roles: Set[str] = field(default_factory=set)

    attributes: Dict[str, Any] = field(default_factory=dict)

    active: bool = True


# ---------------------------------------------------
# RESOURCE
# ---------------------------------------------------

@dataclass
class Resource:

    id: str

    type: str

    owner: Optional[str] = None

    attributes: Dict[str, Any] = field(default_factory=dict)


# ---------------------------------------------------
# AUDIT ENTRY
# ---------------------------------------------------

@dataclass
class AuditEntry:

    timestamp: datetime

    user: str

    permission: str

    resource: str

    decision: str

    reason: str


# ---------------------------------------------------
# POLICY BASE CLASS
# ---------------------------------------------------

class Policy(ABC):

    @abstractmethod
    def evaluate(
        self,
        user: User,
        permission: Permission,
        resource: Resource,
    ) -> Decision:
        pass


# ---------------------------------------------------
# ROLE POLICY
# ---------------------------------------------------

class RolePolicy(Policy):

    def __init__(self, roles: Dict[str, Role]):

        self.roles = roles

    def evaluate(
        self,
        user,
        permission,
        resource,
    ) -> Decision:

        for role_name in user.roles:

            role = self.roles.get(role_name)

            if role is None:
                continue

            if permission in role.permissions:

                return Decision.ALLOW

        return Decision.ABSTAIN


# ---------------------------------------------------
# ATTRIBUTE POLICY
# ---------------------------------------------------

class AttributePolicy(Policy):

    def evaluate(
        self,
        user,
        permission,
        resource,
    ) -> Decision:

        if resource.owner == user.id:

            return Decision.ALLOW

        if user.attributes.get("department") == resource.attributes.get("department"):

            return Decision.ALLOW

        return Decision.ABSTAIN


# ---------------------------------------------------
# DENY POLICY
# ---------------------------------------------------

class DenyInactiveUsersPolicy(Policy):

    def evaluate(
        self,
        user,
        permission,
        resource,
    ):

        if not user.active:

            return Decision.DENY

        return Decision.ABSTAIN


# ---------------------------------------------------
# AUTHORIZATION ENGINE
# ---------------------------------------------------

class AuthorizationEngine:

    def __init__(self):

        self.roles: Dict[str, Role] = {}

        self.users: Dict[str, User] = {}

        self.policies: List[Policy] = []

        self.audit_log: List[AuditEntry] = []

    def register_role(self, role: Role):

        self.roles[role.name] = role

    def register_user(self, user: User):

        self.users[user.id] = user

    def add_policy(self, policy: Policy):

        self.policies.append(policy)

    def authorize(
        self,
        user_id: str,
        permission: Permission,
        resource: Resource,
    ) -> bool:

        user = self.users[user_id]

        for policy in self.policies:

            result = policy.evaluate(
                user,
                permission,
                resource,
            )

            if result == Decision.DENY:

                self.audit_log.append(
                    AuditEntry(
                        timestamp=datetime.utcnow(),
                        user=user.username,
                        permission=permission.name,
                        resource=resource.id,
                        decision="DENY",
                        reason=policy.__class__.__name__,
                    )
                )

                return False

            if result == Decision.ALLOW:

                self.audit_log.append(
                    AuditEntry(
                        timestamp=datetime.utcnow(),
                        user=user.username,
                        permission=permission.name,
                        resource=resource.id,
                        decision="ALLOW",
                        reason=policy.__class__.__name__,
                    )
                )

                return True

        return False


# ---------------------------------------------------
# EXAMPLE
# ---------------------------------------------------

if __name__ == "__main__":

    read = Permission("document.read")

    admin = Role("admin")

    admin.add_permission(read)

    alice = User(
        id=str(uuid.uuid4()),
        username="alice",
    )

    alice.roles.add("admin")

    resource = Resource(
        id="doc-001",
        type="document",
    )

    engine = AuthorizationEngine()

    engine.register_role(admin)

    engine.register_user(alice)

    engine.add_policy(DenyInactiveUsersPolicy())

    engine.add_policy(RolePolicy(engine.roles))

    engine.add_policy(AttributePolicy())

    print(
        engine.authorize(
            alice.id,
            read,
            resource,
        )
    )
